INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct07144293', '노화 세포 제거, HIV 환자의 건강한 노년에 새로운 희망이 될까요?', '노화 세포 제거, HIV 환자의 건강한 노년에 새로운 희망이 될까요?', 'ClinicalTrials.gov (PHASE2)', 'NCT07144293', '노화', 'pro', '["브라운바이오텍 연구팀은 ClinicalTrials.gov에 발표된 2상 임상 연구를 통해 다사티닙과 퀘르세틴(D+Q)","병용 요법이 HIV를 가진 고령 환자들의 신체 기능 및 노화 세포 제거에 긍정적인 영향을 미칠 수 있는지 탐색하고","있음을 전합니다. 이 연구는 만성 질환과 노화가 복합적으로 작용하는 문제에 대한 새로운 치료 전략의 가능성을 제시합니다."]', NULL, NULL, '원본 연구 참조 필요', '브라운바이오텍 연구팀은 ClinicalTrials.gov에 발표된 2상 임상 연구를 통해 다사티닙과 퀘르세틴(D+Q) 병용 요법이 HIV를 가진 고령 환자들의 신체 기능 및 노화 세포 제거에 긍정적인 영향을 미칠 수 있는지 탐색하고 있음을 전합니다. 이 연구는 만성 질환과 노화가 복합적으로 작용하는 문제에 대한 새로운 치료 전략의 가능성을 제시합니다.', '2026-02-13');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct06475456', '심장 쇼크 환자의 골든타임, 의료 협력으로 지킬 수 있을까요?', '심장 쇼크 환자의 골든타임, 의료 협력으로 지킬 수 있을까요?', 'ClinicalTrials.gov ()', 'NCT06475456', '심혈관', 'pro', '["이탈리아에서 심근경색 합병증인 심장 쇼크(Cardiogenic Shock) 환자의 생","존율을 높이기 위한 새로운 의료 협력 프로토콜의 임상시험 계획이 등록되었습니다. 지역","병원과 전문 병원 간의 신속한 연계를 통해 30일 사망률을 낮추는 것이 목표입니다."]', NULL, NULL, '원본 연구 참조 필요', '이탈리아에서 심근경색 합병증인 심장 쇼크(Cardiogenic Shock) 환자의 생존율을 높이기 위한 새로운 의료 협력 프로토콜의 임상시험 계획이 등록되었습니다. 지역 병원과 전문 병원 간의 신속한 연계를 통해 30일 사망률을 낮추는 것이 목표입니다.', '2026-02-13');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct05758246', '노화가 불러오는 감염 취약성, ''노화 세포''가 열쇠일까요?', '노화가 불러오는 감염 취약성, ''노화 세포''가 열쇠일까요?', 'ClinicalTrials.gov (PHASE2)', 'NCT05758246', '노화', 'pro', '["고령층의 패혈증 취약성 문제를 해결하기 위해, 브라운바이오텍은 ''노화 세포(Senescent Cells)''가 중요한 원인일 수 있다는 가설에 주","목하고 있습니다. 현재 진행 중인 ''STOP-Sepsis'' 임상 연구는 노화 세포를 선택적으로 제거하는 ''세놀리틱스(Senolytics)'' 약물","인 피세틴(Fisetin)이 패혈증의 진행과 심각성을 줄일 수 있는지 탐색하며, 고령층 감염병 예방 및 치료에 새로운 희망을 제시하고 있습니다."]', NULL, NULL, '원본 연구 참조 필요', '고령층의 패혈증 취약성 문제를 해결하기 위해, 브라운바이오텍은 ''노화 세포(Senescent Cells)''가 중요한 원인일 수 있다는 가설에 주목하고 있습니다. 현재 진행 중인 ''STOP-Sepsis'' 임상 연구는 노화 세포를 선택적으로 제거하는 ''세놀리틱스(Senolytics)'' 약물인 피세틴(Fisetin)이 패혈증의 진행과 심각성을 줄일 수 있는지 탐', '2026-02-13');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-64898-2026-01-15-26344224', '미토콘드리아 유전자 변이, 파킨슨병 위험과 깊은 연관성을 보입니다: 브라질 아마존 지역 연구 결과', '미토콘드리아 유전자 변이, 파킨슨병 위험과 깊은 연관성을 보입니다: 브라질 아마존 지역 연구 결과', 'medrxiv (preprint)', '10.64898/2026.01.15.26344224', '노화', 'pro', '["최근 발표된 연구에 따르면, 우리 몸의 에너지 공장인 미토콘드리아의 유전자 변이(mtSNVs)가 파킨슨병(PD) 발생 위험과 밀접하게 연관되어 ","인구(admixed population)를 대상으로 한 이번 연구에서는 세 가지 새로운 미토콘드리아 변이와 함께, 여러 변이의 복합적인 영향을 ","PRS)''가 파킨슨병 위험을 약 3.6배 높일 수 있음을 보여주었습니다. 이는 미토콘드리아 유전적 특성이 파킨슨병과 같은 신경 퇴행성 질환의 민"]', NULL, NULL, '원본 연구 참조 필요', '최근 발표된 연구에 따르면, 우리 몸의 에너지 공장인 미토콘드리아의 유전자 변이(mtSNVs)가 파킨슨병(PD) 발생 위험과 밀접하게 연관되어 있다고 합니다. 특히, 브라질 아마존 지역의 혼합 인구(admixed population)를 대상으로 한 이번 연구에서는 세 가지 새로운 미토콘드리아 변이와 함께, 여러 변이의 복합적인 영향을 반영하는 ''미토콘드리아', '2026-02-13');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1101-2024-06-26-600909', '암세포 에너지 대사의 새로운 비밀: LDH의 복합적 역할 규명', '암세포 에너지 대사의 새로운 비밀: LDH의 복합적 역할 규명', 'biorxiv (preprint)', '10.1101/2024.06.26.600909', '노화', 'pro', '["안녕하세요, 브라운바이오텍입니다. 최근 Zeng 등 연구진의 사전 공개 논문(2026)에 따르면, 젖산 탈수소효소(LDH)는 암세포의 에너지 대","을 합니다. LDH A 또는 B 유전자를 단독으로 제거했을 때는 해당과정, TCA 회로, 산화적 인산화에 미치는 영향이 미미했지만, LDH 유전","한 주요 에너지 생산 경로들이 효과적으로 억제됨이 밝혀졌습니다. 이 연구는 효소의 속도론과 열역학적 조절이 대사 경로에 미치는 심오한 영향을 밝"]', NULL, NULL, '원본 연구 참조 필요', '안녕하세요, 브라운바이오텍입니다. 최근 Zeng 등 연구진의 사전 공개 논문(2026)에 따르면, 젖산 탈수소효소(LDH)는 암세포의 에너지 대사 조절에 있어 기존에 알려진 것보다 훨씬 복합적인 역할을 합니다. LDH A 또는 B 유전자를 단독으로 제거했을 때는 해당과정, TCA 회로, 산화적 인산화에 미치는 영향이 미미했지만, LDH 유전자 제거와 특정 ', '2026-02-13');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct04623593', '목 디스크 수술, 장기적으로 더 현명한 선택은 무엇일까요? - CACES 임상 연구', '목 디스크 수술, 장기적으로 더 현명한 선택은 무엇일까요? - CACES 임상 연구', 'ClinicalTrials.gov (NA)', 'NCT04623593', '노화', 'pro', '["퇴행성 경추 추간판 질환(CDDD) 수술법 중 경추 전방 유합술(ACDF)과 경추 추간판 치환술(ACDA)의 장기적인 비용 효과성을 비교하는 연","이 연구는 ACDA가 초기 비용은 높지만 인접 분절 병증(CASP)을 예방하여 장기적으로 더 나은 대안이 될 수 있는지 사회적 관점에서 탐색합니","고령화 시대에 중요한 의료 정책 결정을 위한 고품질의 증거를 마련할 것으로 기대됩니다."]', NULL, NULL, '원본 연구 참조 필요', '퇴행성 경추 추간판 질환(CDDD) 수술법 중 경추 전방 유합술(ACDF)과 경추 추간판 치환술(ACDA)의 장기적인 비용 효과성을 비교하는 연구가 진행 중입니다. 이 연구는 ACDA가 초기 비용은 높지만 인접 분절 병증(CASP)을 예방하여 장기적으로 더 나은 대안이 될 수 있는지 사회적 관점에서 탐색합니다. 고령화 시대에 중요한 의료 정책 결정을 위한 ', '2026-02-12');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-64898-2026-01-12-26343913', '헌팅턴병, 증상 발현 전 뇌 에너지 변화를 읽어낼 수 있을까요?', '헌팅턴병, 증상 발현 전 뇌 에너지 변화를 읽어낼 수 있을까요?', 'medrxiv (preprint)', '10.64898/2026.01.12.26343913', '노화', 'pro', '["최근 연구에 따르면 헌팅턴병 환자의 뇌 에너지 대사(bioenergetic metabolism)","이상이 증상 발현보다 먼저 나타나며, 뇌 위축(atrophy)과 밀접하게 연관되어 있다고 합니다.","이는 헌팅턴병의 조기 진단을 위한 새로운 생체 지표(biomarker) 개발 가능성을 시사합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에 따르면 헌팅턴병 환자의 뇌 에너지 대사(bioenergetic metabolism) 이상이 증상 발현보다 먼저 나타나며, 뇌 위축(atrophy)과 밀접하게 연관되어 있다고 합니다. 이는 헌팅턴병의 조기 진단을 위한 새로운 생체 지표(biomarker) 개발 가능성을 시사합니다.', '2026-02-12');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1101-2024-06-26-600909-1', 'LDH의 재발견: 암세포 에너지 대사의 정교한 ''열쇠''를 찾아서', 'LDH의 재발견: 암세포 에너지 대사의 정교한 ''열쇠''를 찾아서', 'biorxiv (preprint)', '10.1101/2024.06.26.600909', '노화', 'pro', '["저희 브라운바이오텍 장수과학 연구팀은 최근 Zeng 외 연구진이 발표한 초록(preprint)을 통해 젖산 탈수소효소(LDH)가 암세포의 에너지","GNE-140)를 병행했을 때 해당과정, 시트르산 회로, 산화적 인산화 등 암세포의 주요 에너지 생성 과정들이 크게 억제된다는 사실을 보여줍니다","적으로 암세포의 에너지 위기와 사멸을 유도할 수 있다는 점을 시사합니다. 이 발견은 효소의 작용 방식(역학)과 에너지 변화(열역학)의 복합적인 "]', NULL, NULL, '원본 연구 참조 필요', '저희 브라운바이오텍 장수과학 연구팀은 최근 Zeng 외 연구진이 발표한 초록(preprint)을 통해 젖산 탈수소효소(LDH)가 암세포의 에너지 대사를 어떻게 정교하게 조절하는지 밝혀낸 연구를 소개해 드립니다. 이 연구는 LDH 유전자 제거와 억제제(GNE-140)를 병행했을 때 해당과정, 시트르산 회로, 산화적 인산화 등 암세포의 주요 에너지 생성 과정들', '2026-02-12');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1101-2023-01-11-523642', '노화 세포의 놀라운 생존 전략: 우리 몸에 어떤 영향을 줄까요?', '노화 세포의 놀라운 생존 전략: 우리 몸에 어떤 영향을 줄까요?', 'biorxiv (preprint)', '10.1101/2023.01.11.523642', '노화', 'basic', '["최근 연구에 따르면, 노화 세포(senescent cells)는 ''SCAFs (senescent-cell adhesion fragme","nts)''라는 조각을 배출하여 스스로 생존력을 유지한다고 합니다. 하지만 이 조각들은 결국 파열되어 유해 물질을 방출하며, 이는 노화",", 암, 신경퇴행성 질환의 진행에 기여할 수 있습니다. 이 발견은 노화 세포가 우리 몸에 미치는 영향에 대한 새로운 이해를 제공합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에 따르면, 노화 세포(senescent cells)는 ''SCAFs (senescent-cell adhesion fragments)''라는 조각을 배출하여 스스로 생존력을 유지한다고 합니다. 하지만 이 조각들은 결국 파열되어 유해 물질을 방출하며, 이는 노화, 암, 신경퇴행성 질환의 진행에 기여할 수 있습니다. 이 발견은 노화 세포가 우리 몸에 미치', '2026-02-12');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct05758246-1', '노화가 패혈증 위험을 높인다? 세놀리틱스가 해답이 될 수 있을까요?', '노화가 패혈증 위험을 높인다? 세놀리틱스가 해답이 될 수 있을까요?', 'ClinicalTrials.gov (PHASE2)', 'NCT05758246', '노화', 'pro', '["최근 2상 임상 시험 ''STOP-Sepsis'' 연구는 노화 세포(SnCs)가 노인 패혈증(Sepsis)의 주요 원인 중 하나라는","가설 아래, 세놀리틱스(Senolytics) 약물인 피세틴(Fisetin)이 패혈증 진행과 심각도를 줄이는 데 효과적인지 탐색","하고 있습니다. 이 연구는 노화 관련 질환 치료에 새로운 가능성을 제시하며, 건강한 노년을 위한 중요한 진전이 될 수 있습니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 2상 임상 시험 ''STOP-Sepsis'' 연구는 노화 세포(SnCs)가 노인 패혈증(Sepsis)의 주요 원인 중 하나라는 가설 아래, 세놀리틱스(Senolytics) 약물인 피세틴(Fisetin)이 패혈증 진행과 심각도를 줄이는 데 효과적인지 탐색하고 있습니다. 이 연구는 노화 관련 질환 치료에 새로운 가능성을 제시하며, 건강한 노년을 위한 중요한 ', '2026-02-10');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct04623593-1', '목 디스크 치료, 장기적인 관점에서 가장 현명한 선택은 무엇일까요?', '목 디스크 치료, 장기적인 관점에서 가장 현명한 선택은 무엇일까요?', 'ClinicalTrials.gov (NA)', 'NCT04623593', '노화', 'pro', '["브라운바이오텍에서는 목 디스크 환자분들의 삶의 질 향상과 의료비 부담 완화를 위한 중요한 연구를 소개해 드립니다.","이 연구는 척추 유합술(ACDF)과 인공디스크 치환술(ACDA)이라는 두 가지 주요 수술법의 장기적인 비용 효과","성을 사회적 관점에서 비교하며, 고령화 시대에 환자분들과 의료 시스템 모두에게 더 나은 방향을 제시하고자 합니다."]', NULL, NULL, '원본 연구 참조 필요', '브라운바이오텍에서는 목 디스크 환자분들의 삶의 질 향상과 의료비 부담 완화를 위한 중요한 연구를 소개해 드립니다. 이 연구는 척추 유합술(ACDF)과 인공디스크 치환술(ACDA)이라는 두 가지 주요 수술법의 장기적인 비용 효과성을 사회적 관점에서 비교하며, 고령화 시대에 환자분들과 의료 시스템 모두에게 더 나은 방향을 제시하고자 합니다.', '2026-02-10');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1101-2024-11-12-623261', '피부 노화, mRNA로 되돌릴 수 있을까요? 브라운바이오텍의 최신 연구를 소개합니다!', '피부 노화, mRNA로 되돌릴 수 있을까요? 브라운바이오텍의 최신 연구를 소개합니다!', 'biorxiv (preprint)', '10.1101/2024.11.12.623261', '노화', 'pro', '["최근 Li 등 연구팀은 피부 노화의 핵심 원인이 기저 줄기세포(basal stem cells)의 변화와 ATF3","유전자의 발현 감소에 있음을 밝혀냈습니다. 이 연구는 ATF3 mRNA를 이용한 치료가 노화된 피부 세포의 재","생을 촉진하고 콜라겐 생성을 획기적으로 증가시켜 피부 노화의 영향을 되돌릴 수 있는 새로운 가능성을 제시합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 Li 등 연구팀은 피부 노화의 핵심 원인이 기저 줄기세포(basal stem cells)의 변화와 ATF3 유전자의 발현 감소에 있음을 밝혀냈습니다. 이 연구는 ATF3 mRNA를 이용한 치료가 노화된 피부 세포의 재생을 촉진하고 콜라겐 생성을 획기적으로 증가시켜 피부 노화의 영향을 되돌릴 수 있는 새로운 가능성을 제시합니다.', '2026-02-10');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1101-2024-06-26-600909-2', '암세포의 에너지 대사, LDH가 열쇠일까요?', '암세포의 에너지 대사, LDH가 열쇠일까요?', 'biorxiv (preprint)', '10.1101/2024.06.26.600909', '노화', 'pro', '["최근 연구에 따르면, 암세포의 주요 에너지 대사 효소인 LDH(Lactate Dehydrogenase)를 특정 억제제(GNE-140)와 함께 조",", 암세포의 에너지 생산 과정(포도당 대사, TCA 회로, 산화적 인산화)이 효과적으로 저해되는 것이 확인되었습니다. 이러한 현상은 세포 내 N","NADH 균형 변화와 대사 경로의 열역학적 변화에 의해 발생하며, 특히 저산소 환경에서는 암세포의 에너지 위기와 사멸을 더욱 강력하게 유도한다고"]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에 따르면, 암세포의 주요 에너지 대사 효소인 LDH(Lactate Dehydrogenase)를 특정 억제제(GNE-140)와 함께 조절할 때, 암세포의 에너지 생산 과정(포도당 대사, TCA 회로, 산화적 인산화)이 효과적으로 저해되는 것이 확인되었습니다. 이러한 현상은 세포 내 NAD+/NADH 균형 변화와 대사 경로의 열역학적 변화에 의해 발', '2026-02-10');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1007-s10495-025-02251-5', '췌장암 치료의 새로운 희망: PARP 억제제와 노화세포 제거의 시너지 효과는?', '췌장암 치료의 새로운 희망: PARP 억제제와 노화세포 제거의 시너지 효과는?', 'Apoptosis : an international journal on programmed cell death', '10.1007/s10495-025-02251-5', '노화', 'pro', '["최근 연구에 따르면, PARP 억제제는 췌장암 세포에서 세포 자멸사(apoptosis) 외에 세포 노화(cellular senescen","ce)를 유도하여 항암 효과를 발휘한다고 합니다. 약물 중단 시 노화된 암세포가 다시 증식할 수 있지만, Bcl-2 억제제와 같은 노화","세포 제거 약물(senolytic drugs)을 PARP 억제제와 순차적으로 병용하면 치료 효과를 더욱 강화할 수 있음이 밝혀졌습니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에 따르면, PARP 억제제는 췌장암 세포에서 세포 자멸사(apoptosis) 외에 세포 노화(cellular senescence)를 유도하여 항암 효과를 발휘한다고 합니다. 약물 중단 시 노화된 암세포가 다시 증식할 수 있지만, Bcl-2 억제제와 같은 노화세포 제거 약물(senolytic drugs)을 PARP 억제제와 순차적으로 병용하면 치료', '2026-02-10');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1007-s00018-025-05999-w', '브라운바이오텍 연구노트: RGS12, 건강한 임신을 위한 태반 미토콘드리아의 새로운 조절자', '브라운바이오텍 연구노트: RGS12, 건강한 임신을 위한 태반 미토콘드리아의 새로운 조절자', 'Cellular and molecular life sciences : CMLS', '10.1007/s00018-025-05999-w', '노화', 'pro', '["브라운바이오텍 연구팀은 RGS12 단백질이 태반 미토콘드리아 기능에 필수적임을 밝혀냈습니다","이 단백질의 결핍은 미토콘드리아 기능 저하, 에너지 생산 및 항산화 능력 감소를 유발하며, 이는 조산(preterm birth) 등 임신 합병증","이번 연구는 RGS12가 건강한 임신 결과를 개선하기 위한 새로운 치료 표적이 될 잠재력이 있음을 시사합니다."]', NULL, NULL, '원본 연구 참조 필요', '브라운바이오텍 연구팀은 RGS12 단백질이 태반 미토콘드리아 기능에 필수적임을 밝혀냈습니다. 이 단백질의 결핍은 미토콘드리아 기능 저하, 에너지 생산 및 항산화 능력 감소를 유발하며, 이는 조산(preterm birth) 등 임신 합병증 위험 증가와 관련이 있습니다. 이번 연구는 RGS12가 건강한 임신 결과를 개선하기 위한 새로운 치료 표적이 될 잠재력이', '2026-02-10');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct06824285', '뇌 건강, 젊음을 유지하는 열쇠는? 우리 뇌는 어떻게 나이 들어갈까요?', '뇌 건강, 젊음을 유지하는 열쇠는? 우리 뇌는 어떻게 나이 들어갈까요?', 'ClinicalTrials.gov ()', 'NCT06824285', '노화', 'pro', '["최근 임상 연구는 뇌파 검사(EEG)와 인공지능(AI)을 활용하여 건강한 뇌 노화의 생체 표지자를 찾고, 줄","기세포 유래 엑소좀(exosomes)으로 뇌 기능을 회복하는 새로운 가능성을 탐구하고 있습니다. 이 연구는","개인별 뇌 노화 경로를 예측하고 뇌 건강을 보존하기 위한 맞춤형 전략을 개발하는 데 기여할 것으로 기대됩니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 임상 연구는 뇌파 검사(EEG)와 인공지능(AI)을 활용하여 건강한 뇌 노화의 생체 표지자를 찾고, 줄기세포 유래 엑소좀(exosomes)으로 뇌 기능을 회복하는 새로운 가능성을 탐구하고 있습니다. 이 연구는 개인별 뇌 노화 경로를 예측하고 뇌 건강을 보존하기 위한 맞춤형 전략을 개발하는 데 기여할 것으로 기대됩니다.', '2026-02-08');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1038-s41574-025-01187-9', '대사 질환, 노화 세포가 핵심 열쇠가 될 수 있을까요?', '대사 질환, 노화 세포가 핵심 열쇠가 될 수 있을까요?', 'Nature reviews. Endocrinology', '10.1038/s41574-025-01187-9', '내분비', 'pro', '["최근 연구에 따르면 우리 몸의 ''노화 세포(cellular senescence)''가 비만 및 대사","질환의 발생과 악화에 중요한 역할을 한다고 합니다. 이러한 노화 세포를 표적으로 하는 새로운 치","료법(senotherapeutics)이 미래 대사 질환 예방 및 치료에 큰 희망을 제시하고 있습니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에 따르면 우리 몸의 ''노화 세포(cellular senescence)''가 비만 및 대사 질환의 발생과 악화에 중요한 역할을 한다고 합니다. 이러한 노화 세포를 표적으로 하는 새로운 치료법(senotherapeutics)이 미래 대사 질환 예방 및 치료에 큰 희망을 제시하고 있습니다.', '2026-02-08');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct07144293-1', 'HIV와 노화: 새로운 희망, 세포 노화 제거에서 찾을 수 있을까요?', 'HIV와 노화: 새로운 희망, 세포 노화 제거에서 찾을 수 있을까요?', 'ClinicalTrials.gov (PHASE2)', 'NCT07144293', '노화', 'basic', '["HIV 감염인의 가속화된 노화 및 허약 문제를 해결하기 위해, 다사티닙과 퀘르세틴(D+Q) 복합","약물의 안전성과 신체 기능 개선 효과를 평가하는 임상 2상 연구가 진행됩니다. 노화 세포 제거","(senolytic) 약물인 D+Q가 만성 질환자의 건강한 노화에 새로운 희망을 줄지 주목됩니다."]', NULL, NULL, '원본 연구 참조 필요', 'HIV 감염인의 가속화된 노화 및 허약 문제를 해결하기 위해, 다사티닙과 퀘르세틴(D+Q) 복합 약물의 안전성과 신체 기능 개선 효과를 평가하는 임상 2상 연구가 진행됩니다. 노화 세포 제거(senolytic) 약물인 D+Q가 만성 질환자의 건강한 노화에 새로운 희망을 줄지 주목됩니다.', '2026-02-07');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct06824285-1', '우리 뇌는 얼마나 젊을까요? 뇌 노화의 비밀을 EEG로 풀어내다!', '우리 뇌는 얼마나 젊을까요? 뇌 노화의 비밀을 EEG로 풀어내다!', 'ClinicalTrials.gov ()', 'NCT06824285', '노화', 'pro', '["브라운바이오텍 장수과학 리서치팀은 최근 발표된 연구를 통해 뇌 노화의 핵심 바이오마커를 비침습적으로 탐색하고",", 줄기세포 유래 엑소좀과 인공지능(AI)을 활용하여 건강한 뇌 노화를 위한 새로운 길을 모색하고 있습니다.","이 연구는 뇌 건강을 조기에 예측하고 맞춤형 개입 전략을 개발하는 데 중요한 기여를 할 것으로 기대됩니다."]', NULL, NULL, '원본 연구 참조 필요', '브라운바이오텍 장수과학 리서치팀은 최근 발표된 연구를 통해 뇌 노화의 핵심 바이오마커를 비침습적으로 탐색하고, 줄기세포 유래 엑소좀과 인공지능(AI)을 활용하여 건강한 뇌 노화를 위한 새로운 길을 모색하고 있습니다. 이 연구는 뇌 건강을 조기에 예측하고 맞춤형 개입 전략을 개발하는 데 중요한 기여를 할 것으로 기대됩니다.', '2026-02-07');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-nct05758246-2', '노년층 패혈증, ''늙은 세포''가 새로운 희망이 될 수 있을까요?', '노년층 패혈증, ''늙은 세포''가 새로운 희망이 될 수 있을까요?', 'ClinicalTrials.gov (PHASE2)', 'NCT05758246', '노화', 'pro', '["브라운바이오텍입니다. ''STOP-Sepsis'' 임상 2상 연구는 노년층 패혈증의 심각성에 노화 세포(SnCs",")가 미치는 영향을 밝히고, 세놀리틱 약물 피세틴(Fisetin)이 이를 개선할 수 있는지 탐색합니다. 이","연구는 노화 관련 질병 치료의 새로운 가능성을 제시하며, 향후 노년층 건강 증진에 기여할 것으로 기대됩니다."]', NULL, NULL, '원본 연구 참조 필요', '브라운바이오텍입니다. ''STOP-Sepsis'' 임상 2상 연구는 노년층 패혈증의 심각성에 노화 세포(SnCs)가 미치는 영향을 밝히고, 세놀리틱 약물 피세틴(Fisetin)이 이를 개선할 수 있는지 탐색합니다. 이 연구는 노화 관련 질병 치료의 새로운 가능성을 제시하며, 향후 노년층 건강 증진에 기여할 것으로 기대됩니다.', '2026-02-07');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-64898-2026-01-12-26343913-1', '뇌 에너지 대사, 헌팅턴병의 미래를 밝히다?', '뇌 에너지 대사, 헌팅턴병의 미래를 밝히다?', 'medrxiv (preprint)', '10.64898/2026.01.12.26343913', '노화', 'pro', '["헌팅턴병(HD) 연구에서 뇌의 에너지 대사 이상이 질병 초기부터 나타나며, 증상 발현 전 뇌 위축과","연관된다는 중요한 사실이 밝혀졌습니다. 이 발견은 뇌 에너지 대사 변화가 헌팅턴병의 조기 바이오마","커로 활용될 수 있는 가능성을 제시하며, 향후 예방 및 치료 전략 개발에 기여할 것으로 기대됩니다."]', NULL, NULL, '원본 연구 참조 필요', '헌팅턴병(HD) 연구에서 뇌의 에너지 대사 이상이 질병 초기부터 나타나며, 증상 발현 전 뇌 위축과 연관된다는 중요한 사실이 밝혀졌습니다. 이 발견은 뇌 에너지 대사 변화가 헌팅턴병의 조기 바이오마커로 활용될 수 있는 가능성을 제시하며, 향후 예방 및 치료 전략 개발에 기여할 것으로 기대됩니다.', '2026-02-07');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-64898-2026-01-06-26343442', '파킨슨병과 조현병, 놀라운 유전적 연결고리가 밝혀지다?', '파킨슨병과 조현병, 놀라운 유전적 연결고리가 밝혀지다?', 'medrxiv (preprint)', '10.64898/2026.01.06.26343442', '노화', 'pro', '["최근 연구에 따르면 파킨슨병과 조현병은 임상적으로 다르지만 ''RAI1'' 유전자 변이 등","공통된 유전적 취약성을 공유할 수 있습니다. 특히 미토콘드리아 기능 이상과 염증이 두","질환의 공통적인 발병 메커니즘으로 지목되어, 뇌 건강 관리에 새로운 시사점을 제공합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에 따르면 파킨슨병과 조현병은 임상적으로 다르지만 ''RAI1'' 유전자 변이 등 공통된 유전적 취약성을 공유할 수 있습니다. 특히 미토콘드리아 기능 이상과 염증이 두 질환의 공통적인 발병 메커니즘으로 지목되어, 뇌 건강 관리에 새로운 시사점을 제공합니다.', '2026-02-07');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1111-acel-70368', '태반 줄기세포, 노화 세포를 젊게 되돌릴 수 있을까요?', '태반 줄기세포, 노화 세포를 젊게 되돌릴 수 있을까요?', 'Aging cell', '10.1111/acel.70368', '노화', 'basic', '["최근 연구에서 인간 태반 줄기세포에서 분비되는 물질(secretome)이 노화 세포의","특성을 완화하는 효과가 있다는 사실이 밝혀졌습니다. 특히, 세포외 소포(EVs)는","노화 관련 염증 반응을 줄이고 DNA 손상을 억제하는 데 기여하는 것으로 나타났습니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에서 인간 태반 줄기세포에서 분비되는 물질(secretome)이 노화 세포의 특성을 완화하는 효과가 있다는 사실이 밝혀졌습니다. 특히, 세포외 소포(EVs)는 노화 관련 염증 반응을 줄이고 DNA 손상을 억제하는 데 기여하는 것으로 나타났습니다.', '2026-02-06');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1111-1744-7917-70191', '누에가 알려주는 장수의 비밀? NAD⁺와 니코틴산의 놀라운 효능!', '누에가 알려주는 장수의 비밀? NAD⁺와 니코틴산의 놀라운 효능!', 'Insect science', '10.1111/1744-7917.70191', '노화', 'basic', '["최근 곤충학 저널에 발표된 연구에 따르면 누에를 통해 NAD⁺ 대사가 수명 연장에","중요한 역할을 한다는 사실이 밝혀졌습니다. 특히, 니코틴산(NA) 보충이 노화 관련","변화를 개선하고 수명을 연장하는 데 도움이 될 수 있다는 흥미로운 결과가 나왔습니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 곤충학 저널에 발표된 연구에 따르면 누에를 통해 NAD⁺ 대사가 수명 연장에 중요한 역할을 한다는 사실이 밝혀졌습니다. 특히, 니코틴산(NA) 보충이 노화 관련 변화를 개선하고 수명을 연장하는 데 도움이 될 수 있다는 흥미로운 결과가 나왔습니다.', '2026-02-06');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1101-2024-08-05-606704', '미토콘드리아 건강, 칼슘 신호에 달렸다?! Mfn2의 숨겨진 역할 발견!', '미토콘드리아 건강, 칼슘 신호에 달렸다?! Mfn2의 숨겨진 역할 발견!', 'biorxiv (preprint)', '10.1101/2024.08.05.606704', '노화', 'basic', '["최근 연구에서 미토콘드리아 외막 융합 단백질인 Mfn2가 NCLX를 통해 미토콘드리아 내 칼","슘 방출을 조절하는 새로운 역할을 한다는 사실이 밝혀졌습니다. 이는 ROS에 의한 미토콘드리","아 손상과 신경퇴행성 질환 및 대사 질환 사이의 연관성을 이해하는 데 중요한 단서를 제공합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에서 미토콘드리아 외막 융합 단백질인 Mfn2가 NCLX를 통해 미토콘드리아 내 칼슘 방출을 조절하는 새로운 역할을 한다는 사실이 밝혀졌습니다. 이는 ROS에 의한 미토콘드리아 손상과 신경퇴행성 질환 및 대사 질환 사이의 연관성을 이해하는 데 중요한 단서를 제공합니다.', '2026-02-06');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1101-2023-01-11-523642-1', '늙은 세포가 조각을 버리는 새로운 방식, 우리 몸에 어떤 영향을 줄까요?', '늙은 세포가 조각을 버리는 새로운 방식, 우리 몸에 어떤 영향을 줄까요?', 'biorxiv (preprint)', '10.1101/2023.01.11.523642', '노화', 'basic', '["최근 연구에서 늙은 세포(senescent cell)가 세포 간 접착을 통해 손상된 세포","소기관을 포함한 조각(SCAF)을 배출한다는 사실이 밝혀졌습니다. 이 과정은 늙은 세포의","생존에는 도움이 되지만, 주변 조직에 손상을 유발하여 노화 및 질병과 관련될 수 있습니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에서 늙은 세포(senescent cell)가 세포 간 접착을 통해 손상된 세포 소기관을 포함한 조각(SCAF)을 배출한다는 사실이 밝혀졌습니다. 이 과정은 늙은 세포의 생존에는 도움이 되지만, 주변 조직에 손상을 유발하여 노화 및 질병과 관련될 수 있습니다.', '2026-02-06');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1038-s41574-025-01187-9-1', '노화 세포, 대사 질환 치료의 열쇠가 될 수 있을까요?', '노화 세포, 대사 질환 치료의 열쇠가 될 수 있을까요?', 'Nature reviews. Endocrinology', '10.1038/s41574-025-01187-9', '내분비', 'pro', '["최근 Nature Reviews Endocrinology에 발표된 연구에 따르면, 노화 세포 (senescent c","ells)를 표적으로 하는 치료법 (senotherapeutics)이 비만과 대사 질환 치료에 새로운 가능성을 제시","하고 있습니다. 노화 세포는 대사 기능 장애를 악화시키는 악순환을 유발할 수 있으며, 이를 제어하는 것이 중요합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 Nature Reviews Endocrinology에 발표된 연구에 따르면, 노화 세포 (senescent cells)를 표적으로 하는 치료법 (senotherapeutics)이 비만과 대사 질환 치료에 새로운 가능성을 제시하고 있습니다. 노화 세포는 대사 기능 장애를 악화시키는 악순환을 유발할 수 있으며, 이를 제어하는 것이 중요합니다.', '2026-02-06');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1177-11206721261419640', '녹내장, 비타민과 영양제로 시력을 지킬 수 있을까요?', '녹내장, 비타민과 영양제로 시력을 지킬 수 있을까요?', 'European journal of ophthalmology', '10.1177/11206721261419640', '노화', 'basic', '["녹내장은 주요 실명 원인 중 하나이며, 현재 완치법은 없습니다","최근 연구에 따르면 특정 비타민과 영양제(Nutraceuticals)가 망막 신경절 세포를 보호하고 안압을 낮추는 데 도움을 줄 수 있다고 합니","하지만 아직 연구 단계이며, 맹신해서는 안 됩니다."]', NULL, NULL, '원본 연구 참조 필요', '녹내장은 주요 실명 원인 중 하나이며, 현재 완치법은 없습니다. 최근 연구에 따르면 특정 비타민과 영양제(Nutraceuticals)가 망막 신경절 세포를 보호하고 안압을 낮추는 데 도움을 줄 수 있다고 합니다. 하지만 아직 연구 단계이며, 맹신해서는 안 됩니다.', '2026-02-05');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1111-1744-7917-70191-1', '누에가 알려주는 장수의 비밀? NAD⁺와 노화 방지의 연관성', '누에가 알려주는 장수의 비밀? NAD⁺와 노화 방지의 연관성', 'Insect science', '10.1111/1744-7917.70191', '노화', 'pro', '["최근 연구에서 누에가 NAD⁺ 대사와 관련된 노화 연구의 새로운 모델로 제시","되었습니다. 누에의 BmNmnat1 효소와 니코틴산(NA) 보충이 노화 관련","변화를 늦추고 수명을 연장하는 데 기여할 수 있다는 가능성이 밝혀졌습니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에서 누에가 NAD⁺ 대사와 관련된 노화 연구의 새로운 모델로 제시되었습니다. 누에의 BmNmnat1 효소와 니코틴산(NA) 보충이 노화 관련 변화를 늦추고 수명을 연장하는 데 기여할 수 있다는 가능성이 밝혀졌습니다.', '2026-02-05');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1038-s41574-025-01187-9-2', '나이 든 세포가 대사 질환의 원인? 노화 세포 제거 치료의 가능성', '나이 든 세포가 대사 질환의 원인? 노화 세포 제거 치료의 가능성', 'Nature reviews. Endocrinology', '10.1038/s41574-025-01187-9', '내분비', 'pro', '["최근 연구에 따르면 세포 노화(Cellular senescence)는 대사 질환 악화에 중요한 역할을","합니다. 노화 세포를 제거하는 치료법(Senotherapeutics)이 비만 및 대사 질환 치료에","새로운 희망을 제시할 수 있으며, 이를 위한 임상 시험 설계 및 실행에 대한 고려 사항을 논의합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에 따르면 세포 노화(Cellular senescence)는 대사 질환 악화에 중요한 역할을 합니다. 노화 세포를 제거하는 치료법(Senotherapeutics)이 비만 및 대사 질환 치료에 새로운 희망을 제시할 수 있으며, 이를 위한 임상 시험 설계 및 실행에 대한 고려 사항을 논의합니다.', '2026-02-05');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1016-j-ejphar-2026-178620', '나이가 들수록 숨쉬기 힘든 이유, 해답은 자연에서 찾을 수 있을까요?', '나이가 들수록 숨쉬기 힘든 이유, 해답은 자연에서 찾을 수 있을까요?', 'European journal of pharmacology', '10.1016/j.ejphar.2026.178620', '노화', 'pro', '["노화는 호흡기 질환의 주요 위험 요인입니다. 최근 연구에 따르면 세포 노화, 염증 노화 (In","flammaging), 면역 노화 (Immunosenescence)를 조절하는 천연 세놀리틱스","(Senotherapeutics)가 노년층의 호흡기 건강 유지에 도움이 될 수 있다고 합니다."]', NULL, NULL, '원본 연구 참조 필요', '노화는 호흡기 질환의 주요 위험 요인입니다. 최근 연구에 따르면 세포 노화, 염증 노화 (Inflammaging), 면역 노화 (Immunosenescence)를 조절하는 천연 세놀리틱스 (Senotherapeutics)가 노년층의 호흡기 건강 유지에 도움이 될 수 있다고 합니다.', '2026-02-05');

INSERT INTO articles (slug, title, original_title, journal, doi, topic, tier, key_messages, study_n, study_endpoint, study_limitations, clinical_insight, published_at)
VALUES ('ll-10-1002-ddr-70221', '피부 질환, 미토콘드리아 기능 이상과 관련 있다?!', '피부 질환, 미토콘드리아 기능 이상과 관련 있다?!', 'Drug development research', '10.1002/ddr.70221', '노화', 'pro', '["최근 연구에서 건선, 백반증, 아토피 피부염과 같은 염증성 피부 질","환의 발병 기전에 미토콘드리아 기능 이상이 중요한 역할을 한다는 사","실이 밝혀졌습니다. 새로운 치료 전략 개발에 대한 가능성을 제시합니다."]', NULL, NULL, '원본 연구 참조 필요', '최근 연구에서 건선, 백반증, 아토피 피부염과 같은 염증성 피부 질환의 발병 기전에 미토콘드리아 기능 이상이 중요한 역할을 한다는 사실이 밝혀졌습니다. 새로운 치료 전략 개발에 대한 가능성을 제시합니다.', '2026-02-05');